### ISSUE TITLE
Can I change wave effects ripple color?

### ISSUE THREAD

**Issue by Micjoyce** [fians/Waves#155]

**Comment by hoxxep** [comment]
This should be possible by overriding the `background` property on the `.waves-effect .waves-ripple` class.

For example, in less, customise `background` and `@gradient`.

```less
.waves-effect {
    > .waves-ripple {
        background: rgba(0,0,0,0.2);
        @gradient: rgba(0,0,0,0.2) 0,rgba(0,0,0,.3) 40%,rgba(0,0,0,.4) 50%,rgba(0,0,0,.5) 60%,rgba(255,255,255,0) 70%;
        background: -webkit-radial-gradient(@gradient);
        background: -o-radial-gradient(@gradient);
        background: -moz-radial-gradient(@gradient);
        background: radial-gradient(@gradient);
    }
}
```
